server:
  port: 5000
spring:
  application:
    name: ibasecloud-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9401/eureka/
zuul:
  routes:
    test:
      path: /test/**
      serviceId: ibasecloud-test

