server:
  port: 9999
spring:
  application:
    name: ibasecloud-test
  cloud:
    nacos:
      discovery:
        server-addr: node1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

